name: Terraform CI/CD

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

env:
  TF_VAR_aws_region: "us-east-1"  # Replace with your desired region

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.3.0" # Adjust to your desired version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.TF_VAR_aws_region }}

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./your-terraform-module-directory # Update with your module directory

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out=tfplan
        working-directory: ./your-terraform-module-directory  # Update with your module directory

  approval:
    name: 'Manual Approval'
    runs-on: ubuntu-latest
    needs: terraform  # This job depends on the terraform job

    steps:
      - name: Approval
        uses: trstringer/manual-approval@v1
        with:
          notify-users: user1, user2  # GitHub usernames to notify
          approvers: user1            # GitHub username required for approval

  apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: approval  # This job depends on the approval job
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'  # Only apply on push to main

    steps:
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./your-terraform-module-directory  # Update with your module directory
